################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Intel Quark
#
#   Abstract:
#
#       This directory contains Intel Quark platform drivers.
#
#   Author:
#
#       Evan Green 4-Dec-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = qrkhostb  \

include $(SRCROOT)/os/minoca.mk

