################################################################################
#
#   Copyright (c) 2012 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Object Manager
#
#   Abstract:
#
#       This library contains the Object Manager. It maintains a global
#       file-system like hierarchy of objects used by many other kernel
#       components including Mm, Io, Ke and Ps.
#
#   Author:
#
#       Evan Green 4-Sep-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = ob.a

BINARYTYPE = klibrary

OBJS = handles.o   \
       obapi.o

include $(SRCROOT)/os/minoca.mk

