################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Object Manager
#
#   Abstract:
#
#       This library contains the Object Manager. It maintains a global
#       file-system like hierarchy of objects used by many other kernel
#       components including Mm, Io, Ke and Ps.
#
#   Author:
#
#       Evan Green 4-Sep-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = ob.a

BINARYTYPE = library

OBJS = handles.o   \
       obapi.o

include $(SRCROOT)/os/minoca.mk

