################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       SPI
#
#   Abstract:
#
#       This directory contains drivers related to SPI peripherals.
#
#   Author:
#
#       Evan Green 14-Aug-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = rk32spi          \

include $(SRCROOT)/os/minoca.mk

