################################################################################
#
#   Copyright (c) 2012 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Runtime Library
#
#   Abstract:
#
#       This library builds the Runtime library used in the kernel and user
#       mode.
#
#   Author:
#
#       Evan Green 26-Jul-2012
#
#   Environment:
#
#       Any
#
################################################################################

DIRS = base    \
       kmode   \
       urtl    \

TESTDIRS = testrtl

include $(SRCROOT)/os/minoca.mk

testrtl: base

