################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Runtime Library
#
#   Abstract:
#
#       This library builds the Runtime library used in the kernel and user
#       mode.
#
#   Author:
#
#       Evan Green 26-Jul-2012
#
#   Environment:
#
#       Any
#
################################################################################

DIRS = base    \
       kmode   \
       rtlc    \

TESTDIRS = testrtl

include $(SRCROOT)/os/minoca.mk

testrtl: base

