################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       ARM GIC Interrupt Controller
#
#   Abstract:
#
#       This library contains the ARM Generic Interrupt Controller UEFI device.
#
#   Author:
#
#       Evan Green 3-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = gic.a

BINARYTYPE = library

OBJS = gic.o     \

include $(SRCROOT)/os/minoca.mk

