################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       ARM GIC Interrupt Controller
#
#   Abstract:
#
#       This library contains the ARM Generic Interrupt Controller UEFI device.
#
#   Author:
#
#       Evan Green 3-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = gic.a

BINARYTYPE = klibrary

OBJS = gic.o     \

include $(SRCROOT)/os/minoca.mk

