################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       YyTest
#
#   Abstract:
#
#       This program compiles the Lexer/Parser Library into an application and
#       tests it.
#
#   Author:
#
#       Evan Green 9-Oct-2015
#
#   Environment:
#
#       Test
#
################################################################################

BINARY = yytest

BINARYTYPE = build

BUILD = yes

BINPLACE = testbin

TARGETLIBS = $(OBJROOT)/os/lib/yy/build/yy.a                     \

OBJS = yytest.o \

include $(SRCROOT)/os/minoca.mk

