################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       app
#
#   Abstract:
#
#       This Chalk module implements application support module, which enables
#       interaction with the outer application.
#
#   Author:
#
#       Evan Green 19-Oct-2016
#
#   Environment:
#
#       POSIX
#
################################################################################

BINARY = app.a

BINARYTYPE = library

include $(SRCDIR)/sources

DIRS = build   \

include $(SRCROOT)/os/minoca.mk

