################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       pthread
#
#   Abstract:
#
#       This module contains POSIX thread support.
#
#   Author:
#
#       Evan Green 4-May-2015
#
#   Environment:
#
#       User Mode C Library
#
################################################################################

DIRS = static

include $(SRCROOT)/os/minoca.mk

