################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       pthread
#
#   Abstract:
#
#       This module contains POSIX thread support.
#
#   Author:
#
#       Evan Green 4-May-2015
#
#   Environment:
#
#       User Mode C Library
#
################################################################################

DIRS = static

include $(SRCROOT)/os/minoca.mk

