################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Debug
#
#   Abstract:
#
#       This module builds the debugger application.
#
#   Author:
#
#       Evan Green 26-Jul-2012
#
#   Environment:
#
#       Debug Client
#
################################################################################

DIRS     = client  \
           dbgext  \
           kexts

include $(SRCROOT)/os/minoca.mk

kexts: dbgext

