################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Blobs
#
#   Abstract:
#
#       This directory contains the binary blobs needed to boot the Raspberry
#       Pi.
#
#   Author:
#
#       Evan Green 26-Oct-2015
#
#   Environment:
#
#       User Mode
#
################################################################################

include $(SRCROOT)/os/minoca.mk

all:
	@cd $(SRCROOT)/os/uefi/plat/rpi2/blobs && \
	    $(MAKE) SRCDIR=$(SRCROOT)/os/uefi/plat/rpi2/blobs

