################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Blobs
#
#   Abstract:
#
#       This directory contains the binary blobs needed to boot the Raspberry
#       Pi.
#
#   Author:
#
#       Evan Green 26-Oct-2015
#
#   Environment:
#
#       User Mode
#
################################################################################

include $(SRCROOT)/os/minoca.mk

all:
	@cd $(SRCROOT)/os/uefi/plat/rpi2/blobs && \
	    $(MAKE) SRCDIR=$(SRCROOT)/os/uefi/plat/rpi2/blobs

