################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       TI OMAP4
#
#   Abstract:
#
#       This library contains the OMAP4 UEFI device support.
#
#   Author:
#
#       Evan Green 3-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = omap4.a

BINARYTYPE = klibrary

OBJS = clock.o     \

include $(SRCROOT)/os/minoca.mk

