################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       TI OMAP4
#
#   Abstract:
#
#       This library contains the OMAP4 UEFI device support.
#
#   Author:
#
#       Evan Green 3-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = omap4.a

BINARYTYPE = library

OBJS = clock.o     \

include $(SRCROOT)/os/minoca.mk

