################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Broadcom
#
#   Abstract:
#
#       This directory contains GPIO drivers for Broadcom SoCs.
#
#   Author:
#
#       Chris Stevens 10-May-2016
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = bc27 \

include $(SRCROOT)/os/minoca.mk

