################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Broadcom
#
#   Abstract:
#
#       This directory contains GPIO drivers for Broadcom SoCs.
#
#   Author:
#
#       Chris Stevens 10-May-2016
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = bc27 \

include $(SRCROOT)/os/minoca.mk

