################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       User Mode Runtime
#
#   Abstract:
#
#       This library contains the user-mode specific stubs needed by the core
#       runtime library (the Rtl library).
#
#   Author:
#
#       Evan Green 20-Feb-2013
#
#   Environment:
#
#       User Mode
#
################################################################################

BINARY = urtl.a

BINARYTYPE = library

OBJS = assert.o  \
       uprint.o  \

include $(SRCROOT)/os/minoca.mk

