################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       KD No-USB
#
#   Abstract:
#
#       This library contains stubs for the KD USB library, for those who don't
#       need USB debug support.
#
#   Author:
#
#       Evan Green 18-Apr-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = kdnousb.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = stubs.o   \

include $(SRCROOT)/os/minoca.mk

