################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       RAM Disk
#
#   Abstract:
#
#       This module implements a simple RAM disk driver.
#
#   Author:
#
#       Evan Green 17-Oct-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = ramdisk.drv

BINARYTYPE = so

BINPLACE = bin

OBJS = ramdisk.o

DYNLIBS = $(BINROOT)/kernel             \

include $(SRCROOT)/os/minoca.mk

