################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Wireless LANs
#
#   Abstract:
#
#       This directory contains wireless LAN drivers.
#
#   Author:
#
#       Chris Stevens 8-Oct-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = rtlw81xx  \

include $(SRCROOT)/os/minoca.mk

