################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Wireless LANs
#
#   Abstract:
#
#       This directory contains wireless LAN drivers.
#
#   Author:
#
#       Chris Stevens 8-Oct-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = rtlw81xx  \

include $(SRCROOT)/os/minoca.mk

