################################################################################
#
#   Copyright (c) 2017 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       x64
#
#   Abstract:
#
#       This library implements AMD64 architecture support routines for the
#       kernel.
#
#   Author:
#
#       Evan Green 8-Jun-2017
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = x64sup.a

BINARYTYPE = klibrary

X64_OBJS = archsup.o   \
           archsupc.o  \
           prochw.o    \
           trap.o      \


include $(SRCROOT)/os/minoca.mk

