################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All rights reserved.
#
#   Module Name:
#
#       SD
#
#   Abstract:
#
#       This file is responsible for building the Secure Digital host controller
#       driver.
#
#   Author:
#
#       Evan Green 16-Mar-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = core      \
       bcm2709   \
       omap4     \
       rk32xx    \

include $(SRCROOT)/os/minoca.mk

bcm2835: core

omap4: core

rk32xx: core

