################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Chalk
#
#   Abstract:
#
#       This directory builds the Chalk language library and command line
#       app.
#
#   Author:
#
#       Evan Green 9-Jun-2016
#
#   Environment:
#
#       User
#
################################################################################

DIRS = app       \
       lib       \

include $(SRCROOT)/os/minoca.mk

app: lib

