################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       SD Rockchip
#
#   Abstract:
#
#       This library contains the Rockchip Secure Digital (card) controller
#       device.
#
#   Author:
#
#       Chris Stevens 16-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

include ../../common

BINARY = sdrk.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = sdrk.o       \

include $(SRCROOT)/os/minoca.mk

