################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       ATA
#
#   Abstract:
#
#       This module implements the driver for the AT Attachment (ATA)
#       controller.
#
#   Author:
#
#       Evan Green 5-Jun-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = ata.drv

BINARYTYPE = so

BINPLACE = bin

OBJS = ata.o

DYNLIBS = $(BINROOT)/kernel             \

include $(SRCROOT)/os/minoca.mk

