################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       DMA Core
#
#   Abstract:
#
#       This module implements the DMA core support library. It provides
#       generic support infrastructure for all DMA controllers.
#
#   Author:
#
#       Evan Green 1-Feb-2016
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = dma.drv

BINARYTYPE = so

BINPLACE = bin

OBJS = dma.o     \

DYNLIBS = $(BINROOT)/kernel \

include $(SRCROOT)/os/minoca.mk

