################################################################################
#
#   Copyright (c) 2012 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Debug
#
#   Abstract:
#
#       This module builds the debugger application.
#
#   Author:
#
#       Evan Green 26-Jul-2012
#
#   Environment:
#
#       Debug Client
#
################################################################################

DIRS     = client  \
           dbgext  \
           kexts

include $(SRCROOT)/os/minoca.mk

kexts: dbgext

