################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Simple Peripheral Bus
#
#   Abstract:
#
#       This directory contains drivers related to Simple Peripheral Busses.
#
#   Author:
#
#       Evan Green 14-Aug-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = core      \
       i2c       \
       spi       \

include $(SRCROOT)/os/minoca.mk

spi i2c: core

