################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Simple Peripheral Bus
#
#   Abstract:
#
#       This directory contains drivers related to Simple Peripheral Busses.
#
#   Author:
#
#       Evan Green 14-Aug-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = core      \
       i2c       \
       spi       \

include $(SRCROOT)/os/minoca.mk

spi i2c: core

