################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       PL-011 UART
#
#   Abstract:
#
#       This library contains the ARM PrimeCell PL-011 UART controller library.
#
#   Author:
#
#       Evan Green 27-Feb-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = pl11.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = pl11.o     \

include $(SRCROOT)/os/minoca.mk

