################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       PL-011 UART
#
#   Abstract:
#
#       This library contains the ARM PrimeCell PL-011 UART controller library.
#
#   Author:
#
#       Evan Green 27-Feb-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = pl11.a

BINARYTYPE = klibrary

OBJS = pl11.o     \

include $(SRCROOT)/os/minoca.mk

