################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Chalk Modules
#
#   Abstract:
#
#       This directory builds the Chalk modules.
#
#   Author:
#
#       Evan Green 28-Aug-2016
#
#   Environment:
#
#       User
#
################################################################################

DIRS = app       \
       bundle    \
       os        \

include $(SRCROOT)/os/minoca.mk

