################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Chalk Modules
#
#   Abstract:
#
#       This directory builds the Chalk modules.
#
#   Author:
#
#       Evan Green 28-Aug-2016
#
#   Environment:
#
#       User
#
################################################################################

DIRS = os        \

include $(SRCROOT)/os/minoca.mk

