################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Image Library
#
#   Abstract:
#
#       This library contains the Image library used to parse executable
#       binaries.
#
#   Author:
#
#       Evan Green 13-Oct-2012
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = im.a

BINARYTYPE = library

BINPLACE = intlib

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

