################################################################################
#
#   Copyright (c) 2012 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Image Library
#
#   Abstract:
#
#       This library contains the Image library used to parse executable
#       binaries.
#
#   Author:
#
#       Evan Green 13-Oct-2012
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = im.a

BINARYTYPE = library

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

