################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Libraries
#
#   Abstract:
#
#       This module contains common libraries used by Minoca applications.
#
#   Author:
#
#       Evan Green 19-Nov-2015
#
#   Environment:
#
#       POSIX
#
################################################################################

DIRS = lzma     \

include $(SRCROOT)/os/minoca.mk

