################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Libraries
#
#   Abstract:
#
#       This module contains common libraries used by Minoca applications.
#
#   Author:
#
#       Evan Green 19-Nov-2015
#
#   Environment:
#
#       POSIX
#
################################################################################

DIRS = chalk    \

include $(SRCROOT)/os/minoca.mk

