################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       PL-110 Video
#
#   Abstract:
#
#       This library contains the ARM PL-110 Video Controller device support.
#
#   Author:
#
#       Evan Green 7-Apr-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include ../common

BINARY = pl110.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = pl110.o     \

include $(SRCROOT)/os/minoca.mk

