################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       PL-110 Video
#
#   Abstract:
#
#       This library contains the ARM PL-110 Video Controller device support.
#
#   Author:
#
#       Evan Green 7-Apr-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = pl110.a

BINARYTYPE = klibrary

OBJS = pl110.o     \

include $(SRCROOT)/os/minoca.mk

