################################################################################
#
#   Copyright (c) 2017 Minoca Corp. All rights reserved.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Sound
#
#   Abstract:
#
#       This directory contains drivers related to sound input and output.
#
#   Author:
#
#       Chris Stevens 29-Mar-2017
#
#   Environment:
#
#       Kernel
#
################################################################################

SOUND_DRIVERS = core     \

DIRS = $(SOUND_DRIVERS) \

include $(SRCROOT)/os/minoca.mk

