################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       File Test
#
#   Abstract:
#
#       This executable implements the file test application.
#
#   Author:
#
#       Evan Green 27-Sep-2013
#
#   Environment:
#
#       User Mode
#
################################################################################

BINARY = filetest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/inc/libc;$(SRCROOT)/os/apps/inc;

OBJS = filetest.o \

DYNLIBS = -lminocaos

include $(SRCROOT)/os/minoca.mk

