################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Base Video Library
#
#   Abstract:
#
#       This module implements basic support for video output via a linear
#       framebuffer.
#
#   Author:
#
#       Evan Green 30-Jan-2013
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = basevid.a

BINARYTYPE = library

OBJS = fontdata.o \
       textvid.o  \

include $(SRCROOT)/os/minoca.mk
