################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       ARMv7 (Boot)
#
#   Abstract:
#
#       This library builds a portion of the ARMv7 kernel library for use in
#       the boot environment.
#
#   Author:
#
#       Evan Green 14-Aug-2013
#
#   Environment:
#
#       Boot
#
################################################################################

BINARY = armboot.a

BINARYTYPE = library

BINPLACE = intlib

ARMV7_OBJS = ../sstep.o    \

include $(SRCROOT)/os/minoca.mk
