################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       ARMv7 (Boot)
#
#   Abstract:
#
#       This library builds a portion of the ARMv7 kernel library for use in
#       the boot environment.
#
#   Author:
#
#       Evan Green 14-Aug-2013
#
#   Environment:
#
#       Boot
#
################################################################################

BINARY = armboot.a

BINARYTYPE = klibrary

ARMV7_OBJS = ../sstep.o    \

include $(SRCROOT)/os/minoca.mk
