################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Test Applications
#
#   Abstract:
#
#       This module contains applications used to test portions of
#       functionality during development of the operating system.
#
#   Author:
#
#       Evan Green 6-May-2013
#
#   Environment:
#
#       User Mode
#
################################################################################

DIRS = aiotest  \
       dbgtest  \
       filetest \
       ktest    \
       mmaptest \
       mnttest  \
       pathtest \
       perftest \
       sigtest  \
       socktest \
       utmrtest \

include $(SRCROOT)/os/minoca.mk

