################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Memory Manager (Boot)
#
#   Abstract:
#
#       This library builds a subset of the Memory Manager library for use in
#       the boot environment.
#
#   Author:
#
#       Evan Green 7-Aug-2013
#
#   Environment:
#
#       Boot
#
################################################################################

BINARY = mmboot.a

BINARYTYPE = library

OBJS = ../mdl.o          \

include $(SRCROOT)/os/minoca.mk

