################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       I2C
#
#   Abstract:
#
#       This directory contains drivers related to I2C peripherals.
#
#   Author:
#
#       Evan Green 7-Sep-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = am3i2c           \
       bcm27i2c         \
       rk3i2c           \

include $(SRCROOT)/os/minoca.mk

