################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       I2C
#
#   Abstract:
#
#       This directory contains drivers related to I2C peripherals.
#
#   Author:
#
#       Evan Green 7-Sep-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = am3i2c           \
       rk3i2c           \

include $(SRCROOT)/os/minoca.mk

