################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Device Removal Test
#
#   Abstract:
#
#       This module implements a test driver that handles device removal.
#
#   Author:
#
#       Chris Stevens 13-May-2013
#
#   Environment:
#
#       Kernel Mode
#
################################################################################

BINARY = devrem.drv

BINARYTYPE = so

BINPLACE = bin

OBJS = devrem.o    \

DYNLIBS = $(BINROOT)/kernel             \

include $(SRCROOT)/os/minoca.mk

