################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Platform
#
#   Abstract:
#
#       This directory platform support drivers.
#
#   Author:
#
#       Evan Green 4-Dec-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = quark     \

include $(SRCROOT)/os/minoca.mk

