################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Platform
#
#   Abstract:
#
#       This directory platform support drivers.
#
#   Author:
#
#       Evan Green 4-Dec-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = goec      \
       quark     \
       rockchip  \
       ti        \

include $(SRCROOT)/os/minoca.mk

