################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Boot Configuration Library
#
#   Abstract:
#
#       This module implements support for boot configuration.
#
#   Author:
#
#       Evan Green 20-Feb-2014
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = bconflib.a

BINARYTYPE = library

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

