################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       SSL Library
#
#   Abstract:
#
#       This library contains a limited SSL support library.
#
#   Author:
#
#       Evan Green 22-Jul-2015
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = ssl.a

BINARYTYPE = klibrary

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

