################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       SSL Library
#
#   Abstract:
#
#       This library contains a limited SSL support library.
#
#   Author:
#
#       Evan Green 22-Jul-2015
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = ssl.a

BINARYTYPE = library

BINPLACE = intlib

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

