################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Terminal Library
#
#   Abstract:
#
#       This library contains the terminal support library.
#
#   Author:
#
#       Evan Green 28-Jul-2014
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = termlib.a

BINARYTYPE = library

BINPLACE = intlib

include sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

