################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Terminal Library
#
#   Abstract:
#
#       This library contains the terminal support library.
#
#   Author:
#
#       Evan Green 28-Jul-2014
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = termlib.a

BINARYTYPE = klibrary

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

