################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Libraries
#
#   Abstract:
#
#       This directory builds common libraries that run in multiple
#       environments.
#
#   Author:
#
#       Evan Green 28-Mar-2014
#
#   Environment:
#
#       Any
#
################################################################################

DIRS = basevid  \
       bconflib \
       crypto   \
       fatlib   \
       im       \
       partlib  \
       rtl      \
       termlib  \
       yy       \

include $(SRCROOT)/os/minoca.mk

fatlib crypto: rtl

