################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Libraries
#
#   Abstract:
#
#       This directory builds common libraries that run in multiple
#       environments.
#
#   Author:
#
#       Evan Green 28-Mar-2014
#
#   Environment:
#
#       Any
#
################################################################################

DIRS = basevid  \
       bconflib \
       crypto   \
       fatlib   \
       im       \
       partlib  \
       rtl      \
       termlib  \

include $(SRCROOT)/os/minoca.mk

fatlib crypto: rtl

