################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Texas Instruments
#
#   Abstract:
#
#       This directory contains platform and SoC support drivers for Texas
#       Instruments devices.
#
#   Author:
#
#       Evan Green 9-Sep-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

ifeq ($(ARCH), $(filter armv7 armv6,$(ARCH)))

DIRS = am3soc    \
       tps65217  \

endif

include $(SRCROOT)/os/minoca.mk

