################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Mmap Test
#
#   Abstract:
#
#       This executable implements the memory map test application.
#
#   Author:
#
#       Chris Stevens 10-Mar-2014
#
#   Environment:
#
#       User
#
################################################################################

BINARY = mmaptest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = mmaptest.o \

DYNLIBS = -lminocaos

include $(SRCROOT)/os/minoca.mk

