################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Terminal
#
#   Abstract:
#
#       This directory contains terminal related drivers, including UART
#       drivers.
#
#   Author:
#
#       Evan Green 21-Nov-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = ser16550  \

include $(SRCROOT)/os/minoca.mk

