################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Terminal
#
#   Abstract:
#
#       This directory contains terminal related drivers, including UART
#       drivers.
#
#   Author:
#
#       Evan Green 21-Nov-2014
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = ser16550  \

include $(SRCROOT)/os/minoca.mk

