################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Win32 Debugger
#
#   Abstract:
#
#       This directory builds the command line and UI versions of the debugger
#       for Windows platforms.
#
#   Author:
#
#       Evan Green 7-May-2013
#
#   Environment:
#
#       Win32
#
################################################################################

DIRS = cmdln    \
       ui       \

include $(SRCROOT)/os/minoca.mk

