################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       AM335x SoC
#
#   Abstract:
#
#       This module implements the TI AM335x SoC support driver.
#
#   Author:
#
#       Evan Green 9-Sep-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = am3soc.drv

BINARYTYPE = so

BINPLACE = bin

OBJS = am3soc.o   \

DYNLIBS = $(BINROOT)/kernel              \

include $(SRCROOT)/os/minoca.mk

