################################################################################
#
#   Copyright (c) 2017 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Broadcom Sound
#
#   Abstract:
#
#       This directory contains sound drivers for Broadcom devices.
#
#   Author:
#
#       Chris Stevens 2-May-2017
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = bc27pwma \

include $(SRCROOT)/os/minoca.mk

