################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Tools
#
#   Abstract:
#
#       This directory compiles build-time tools used to generate final UEFI
#       images.
#
#   Author:
#
#       Evan Green 6-Mar-2014
#
#   Environment:
#
#       Build
#
################################################################################

DIRS = elfconv  \
       genffs   \
       genfv    \
       mkuboot  \

include $(SRCROOT)/os/minoca.mk

plat: core dev

