################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       RTL C
#
#   Abstract:
#
#       This library contains stub functions to allow the Rtl Library to
#       run on top of a standard C library.
#
#   Author:
#
#       Evan Green 23-Oct-2012
#
#   Environment:
#
#       User
#
################################################################################

BINARY = rtlc.a

BINARYTYPE = library

INCLUDES += $(SRCDIR)/..;

OBJS = stubs.o   \

DIRS = build

include $(SRCROOT)/os/minoca.mk

