################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Texas Instruments
#
#   Abstract:
#
#       This directory contains GPIO drivers for Texas Instruments SoCs.
#
#   Author:
#
#       Evan Green 4-Aug-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = omap4 \

include $(SRCROOT)/os/minoca.mk

