################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Mount Test
#
#   Abstract:
#
#       This executable implements the file test application.
#
#   Author:
#
#       Chris Stevens 25-Nov-2013
#
#   Environment:
#
#       User
#
################################################################################

BINARY = mnttest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = mnttest.o \

DYNLIBS = -lminocaos

include $(SRCROOT)/os/minoca.mk


