################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       SD Devices
#
#   Abstract:
#
#       This directory builds UEFI SD device support libraries.
#
#   Author:
#
#       Chris Stevens 17-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

DIRS += core        \
        dwc         \

include $(SRCROOT)/os/minoca.mk

