################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       SD Devices
#
#   Abstract:
#
#       This directory builds UEFI SD device support libraries.
#
#   Author:
#
#       Chris Stevens 17-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

DIRS += core        \
        rk          \

include $(SRCROOT)/os/minoca.mk

