################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       x86
#
#   Abstract:
#
#       This library implements support routines for the Intel IA-32
#       architecture.
#
#   Author:
#
#       Evan Green 29-Jul-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = x86sup.a

BINARYTYPE = library

X86_OBJS = archsup.o   \
           archsupc.o  \
           prochw.o    \
           trap.o      \


include $(SRCROOT)/os/minoca.mk
