################################################################################
#
#   Copyright (c) 2012 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       x86
#
#   Abstract:
#
#       This library implements support routines for the Intel IA-32
#       architecture.
#
#   Author:
#
#       Evan Green 29-Jul-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = x86sup.a

BINARYTYPE = klibrary

X86_OBJS = archsup.o   \
           archsupc.o  \
           prochw.o    \
           trap.o      \


include $(SRCROOT)/os/minoca.mk
