################################################################################
#
#   Copyright (c) 2017 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Image Library (Universal 32-bit)
#
#   Abstract:
#
#       This library contains the Image library used to parse executable
#       binaries in all supported formats.
#
#   Author:
#
#       Evan Green 2-Jun-2017
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = imu.a

BINARYTYPE = klibrary

include $(SRCDIR)/../sources

VPATH += $(SRCDIR)/..:

EXTRA_CPPFLAGS += -m32

include $(SRCROOT)/os/minoca.mk

