################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       ARM Generic Timer
#
#   Abstract:
#
#       This library contains the ARM Generic Timer UEFI device.
#
#   Author:
#
#       Chris Stevens 9-Jun-2016
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = gt.a

BINARYTYPE = klibrary

OBJS = gt.o     \
       gta.o    \

include $(SRCROOT)/os/minoca.mk

