################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       ARM Generic Timer
#
#   Abstract:
#
#       This library contains the ARM Generic Timer UEFI device.
#
#   Author:
#
#       Chris Stevens 9-Jun-2016
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = gt.a

BINARYTYPE = library

OBJS = gt.o     \
       gta.o    \

include $(SRCROOT)/os/minoca.mk

