################################################################################
#
#   Copyright (c) 2017 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Intel Sound
#
#   Abstract:
#
#       This directory contains sound drivers for Intel devices.
#
#   Author:
#
#       Chris Stevens 3-Apr-2017
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = hda \

include $(SRCROOT)/os/minoca.mk

