################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Chalk
#
#   Abstract:
#
#       This library contains the Chalk interpreter, which provides a very
#       basic programming language used to describe things like setup recipes
#       and build configurations.
#
#   Author:
#
#       Evan Green 19-Nov-2015
#
#   Environment:
#
#       POSIX
#
################################################################################

BINARY = chalk.a

BINARYTYPE = library

include $(SRCDIR)/sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

