################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Partition Library
#
#   Abstract:
#
#       This module implements support for disk partitions.
#
#   Author:
#
#       Evan Green 30-Jan-2014
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = partlib.a

BINARYTYPE = library

BINPLACE = intlib

include sources

DIRS = build

include $(SRCROOT)/os/minoca.mk

