################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       OMAP UART
#
#   Abstract:
#
#       This library contains the UART controller library used in Texas
#       Instruments OMAP3 and OMAP4 SoCs.
#
#   Author:
#
#       Evan Green 27-Feb-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = omapuart.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = omapuart.o     \

include $(SRCROOT)/os/minoca.mk

