################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       Ethernet LANs
#
#   Abstract:
#
#       This directory contains Ethernet LAN drivers.
#
#   Author:
#
#       Evan Green 4-Apr-2013
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = am3eth    \
       atl1c     \
       dwceth    \
       e100      \
       e1000     \
       pcnet32   \
       rtl81xx   \
       smsc91c1  \
       smsc95xx  \

include $(SRCROOT)/os/minoca.mk

