################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Ethernet LANs
#
#   Abstract:
#
#       This directory contains Ethernet LAN drivers.
#
#   Author:
#
#       Evan Green 4-Apr-2013
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = am3eth    \
       atl1c     \
       dwceth    \
       e100      \
       rtl81xx   \
       smsc91c1  \
       smsc95xx  \

include $(SRCROOT)/os/minoca.mk

