################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       SD
#
#   Abstract:
#
#       This library contains the generic Secure Digital (card) controller
#       device.
#
#   Author:
#
#       Evan Green 20-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../../common

BINARY = sd.a

BINARYTYPE = klibrary

OBJS = sd.o     \
       sdstd.o  \

include $(SRCROOT)/os/minoca.mk

