################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       SD
#
#   Abstract:
#
#       This library contains the generic Secure Digital (card) controller
#       device.
#
#   Author:
#
#       Evan Green 20-Mar-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../../common

BINARY = sd.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = sd.o     \
       sdstd.o  \

include $(SRCROOT)/os/minoca.mk

