################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       SD DesignWare
#
#   Abstract:
#
#       This library contains the DesignWare Secure Digital (card) controller
#       device.
#
#   Author:
#
#       Chris Stevens 16-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../../common

BINARY = sddwc.a

BINARYTYPE = library

BINPLACE = intlib

OBJS = sddwc.o       \

include $(SRCROOT)/os/minoca.mk

