################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       SD DesignWare
#
#   Abstract:
#
#       This library contains the DesignWare Secure Digital (card) controller
#       device.
#
#   Author:
#
#       Chris Stevens 16-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../../common

BINARY = sddwc.a

BINARYTYPE = klibrary

OBJS = sddwc.o       \

include $(SRCROOT)/os/minoca.mk

