################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Module Name:
#
#       RockChip
#
#   Abstract:
#
#       This directory contains platform and SoC support drivers for RockChip
#       devices.
#
#   Author:
#
#       Evan Green 4-Apr-2016
#
#   Environment:
#
#       Kernel
#
################################################################################

ifeq ($(ARCH), $(filter armv7 armv6,$(ARCH)))

DIRS = rk808     \

endif

include $(SRCROOT)/os/minoca.mk

