################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       RockChip
#
#   Abstract:
#
#       This directory contains platform and SoC support drivers for RockChip
#       devices.
#
#   Author:
#
#       Evan Green 4-Apr-2016
#
#   Environment:
#
#       Kernel
#
################################################################################

ifeq ($(ARCH), $(filter armv7 armv6,$(ARCH)))

DIRS = rk808     \

endif

include $(SRCROOT)/os/minoca.mk

