################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       RockChip
#
#   Abstract:
#
#       This directory contains GPIO drivers for RockChip SoCs.
#
#   Author:
#
#       Evan Green 25-Aug-2015
#
#   Environment:
#
#       Kernel
#
################################################################################

DIRS = rk32 \

include $(SRCROOT)/os/minoca.mk

