################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       Win32 Debugger
#
#   Abstract:
#
#       This directory builds the command line and UI versions of the debugger
#       for Windows platforms.
#
#   Author:
#
#       Evan Green 7-May-2013
#
#   Environment:
#
#       Win32
#
################################################################################

DIRS = cmdln    \
       ui       \

include $(SRCROOT)/os/minoca.mk

