################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Module Name:
#
#       FAT Library
#
#   Abstract:
#
#       This module implements support for the FAT file system.
#
#   Author:
#
#       Evan Green 23-Sep-2012
#
#   Environment:
#
#       Any
#
################################################################################

BINARY = fat.a

BINARYTYPE = library

include $(SRCDIR)/sources

DIRS = build

TESTDIRS = fattest

include $(SRCROOT)/os/minoca.mk

fattest: build

