################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       NS 16550 UART
#
#   Abstract:
#
#       This library contains the NS 16550 UART controller library.
#
#   Author:
#
#       Chris Stevens 10-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = ns16550.a

BINARYTYPE = library

OBJS = ns16550.o     \

include $(SRCROOT)/os/minoca.mk

