################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       NS 16550 UART
#
#   Abstract:
#
#       This library contains the NS 16550 UART controller library.
#
#   Author:
#
#       Chris Stevens 10-Jul-2015
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = ns16550.a

BINARYTYPE = klibrary

OBJS = ns16550.o     \

include $(SRCROOT)/os/minoca.mk

