################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       lzma
#
#   Abstract:
#
#       This executable implements the lzma utility.
#
#   Author:
#
#       Evan Green 13-Jan-2016
#
#   Environment:
#
#       User
#
################################################################################

BINARY = lzma

BINPLACE = bin

BINARYTYPE = app

include $(SRCDIR)/sources

TARGETLIBS = $(OBJROOT)/os/apps/lib/lzma/liblzma.a            \

DIRS = build

include $(SRCROOT)/os/minoca.mk

