################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       PandaFwb
#
#   Abstract:
#
#       This build utility adds the necessary header for USB booting the
#       init application on OMAP4 SoCs.
#
#   Author:
#
#       Evan Green 1-Apr-2014
#
#   Environment:
#
#       Build
#
################################################################################

BINARY = pandafwb

BUILD = yes

BINARYTYPE = build

OBJS = fwbuild.o

include $(SRCROOT)/os/minoca.mk

