################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       PandaFwb
#
#   Abstract:
#
#       This build utility adds the necessary header for USB booting the
#       init application on OMAP4 SoCs.
#
#   Author:
#
#       Evan Green 1-Apr-2014
#
#   Environment:
#
#       Build
#
################################################################################

BINARY = pandafwb

BUILD = yes

BINARYTYPE = build

OBJS = fwbuild.o

include $(SRCROOT)/os/minoca.mk

