################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       ARMv6 (Boot)
#
#   Abstract:
#
#       This library builds a subset of the ARMv6 support library for use in
#       the boot environment.
#
#   Author:
#
#       Chris Stevens 4-Feb-2014
#
#   Environment:
#
#       Boot
#
################################################################################

BINARY = armboot.a

BINARYTYPE = library

ARMV6_OBJS = ../../armv7/sstep.o    \

include $(SRCROOT)/os/minoca.mk
