################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       ARMv6 (Boot)
#
#   Abstract:
#
#       This library builds a subset of the ARMv6 support library for use in
#       the boot environment.
#
#   Author:
#
#       Chris Stevens 4-Feb-2014
#
#   Environment:
#
#       Boot
#
################################################################################

BINARY = armboot.a

BINARYTYPE = klibrary

ARMV6_OBJS = ../../armv7/sstep.o    \

include $(SRCROOT)/os/minoca.mk
