################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       BboneFwb
#
#   Abstract:
#
#       This build utility adds the necessary header for creating the boot
#       region of an SD card on the TI AM335x.
#
#   Author:
#
#       Evan Green 17-Dec-2014
#
#   Environment:
#
#       Build
#
################################################################################

BINARY = bbonefwb

BUILD = yes

BINPLACE = bin

BINARYTYPE = build

OBJS = fwbuild.o

include $(SRCROOT)/os/minoca.mk

