################################################################################
#
#   Copyright (c) 2014 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       BboneFwb
#
#   Abstract:
#
#       This build utility adds the necessary header for creating the boot
#       region of an SD card on the TI AM335x.
#
#   Author:
#
#       Evan Green 17-Dec-2014
#
#   Environment:
#
#       Build
#
################################################################################

BINARY = bbonefwb

BUILD = yes

BINARYTYPE = build

OBJS = fwbuild.o

include $(SRCROOT)/os/minoca.mk

