################################################################################
#
#   Copyright (c) 2014 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       PL-031 RTC
#
#   Abstract:
#
#       This library contains the ARM PrimeCell PL-031 Real Time Clock
#       device support.
#
#   Author:
#
#       Evan Green 7-Apr-2014
#
#   Environment:
#
#       Firmware
#
################################################################################

include $(SRCDIR)/../common

BINARY = pl031.a

BINARYTYPE = library

OBJS = pl031.o     \

include $(SRCROOT)/os/minoca.mk

