################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       DbgExt
#
#   Abstract:
#
#       This module implements the import library for kernel debugger
#       extensions.
#
#   Author:
#
#       Evan Green 8-May-2013
#
#   Environment:
#
#       Debug Client
#
################################################################################

BINARY = dbgext.a

BINARYTYPE = library

BINPLACE = bin

OBJS = extimp.o   \

VPATH += $(SRCDIR)/..:

include $(SRCROOT)/os/minoca.mk

