################################################################################
#
#   Copyright (c) 2012 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Kernel Rtl
#
#   Abstract:
#
#       This library contains kernel-specific functions for the Runtime Library.
#
#   Author:
#
#       Evan Green 26-Jul-2012
#
#   Environment:
#
#       Kernel
#
################################################################################

BINARY = krtl.a

BINARYTYPE = library

INCLUDES += $(SRCDIR)/..;

OBJS = assert.o  \
       kprint.o  \

include $(SRCROOT)/os/minoca.mk

