################################################################################
#
#   Copyright (c) 2013 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Path Test
#
#   Abstract:
#
#       This executable implements the path test application.
#
#   Author:
#
#       Chris Stevens 17-Sept-2013
#
#   Environment:
#
#       User
#
################################################################################

BINARY = pathtest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/inc/libc;$(SRCROOT)/os/apps/inc;

OBJS = pathtest.o \

DYNLIBS = -lminocaos

include $(SRCROOT)/os/minoca.mk

