################################################################################
#
#   Copyright (c) 2013 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Path Test
#
#   Abstract:
#
#       This executable implements the path test application.
#
#   Author:
#
#       Chris Stevens 17-Sept-2013
#
#   Environment:
#
#       User
#
################################################################################

BINARY = pathtest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = pathtest.o \

DYNLIBS = -lminocaos

include $(SRCROOT)/os/minoca.mk

