################################################################################
#
#   Copyright (c) 2016 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Async IO Test
#
#   Abstract:
#
#       This executable implements the asynchronous I/O test app.
#
#   Author:
#
#       Evan Green 27-Jun-2016
#
#   Environment:
#
#       User
#
################################################################################

BINARY = aiotest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = aiotest.o \

include $(SRCROOT)/os/minoca.mk

