################################################################################
#
#   Copyright (c) 2016 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Async IO Test
#
#   Abstract:
#
#       This executable implements the asynchronous I/O test app.
#
#   Author:
#
#       Evan Green 27-Jun-2016
#
#   Environment:
#
#       User
#
################################################################################

BINARY = aiotest

BINPLACE = bin

BINARYTYPE = app

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = aiotest.o \

include $(SRCROOT)/os/minoca.mk

