################################################################################
#
#   Copyright (c) 2015 Minoca Corp. All Rights Reserved
#
#   Binary Name:
#
#       Performance Benchmark Test Library
#
#   Abstract:
#
#       This module implements a stub library for the performance benchmark
#       test application.
#
#   Author:
#
#       Chris Stevens 7-Apr-2015
#
#   Environment:
#
#       User Mode
#
################################################################################

BINARY = perflib.so

BINARYTYPE = so

BINPLACE = bin

ENTRY := 0

INCLUDES += $(SRCROOT)/os/apps/inc/libc;$(SRCROOT)/os/apps/inc;

OBJS = perflib.o  \

include $(SRCROOT)/os/minoca.mk

