################################################################################
#
#   Copyright (c) 2015 Minoca Corp.
#
#    This file is licensed under the terms of the GNU General Public License
#    version 3. Alternative licensing terms are available. Contact
#    info@minocacorp.com for details. See the LICENSE file at the root of this
#    project for complete licensing information.
#
#   Binary Name:
#
#       Performance Benchmark Test Library
#
#   Abstract:
#
#       This module implements a stub library for the performance benchmark
#       test application.
#
#   Author:
#
#       Chris Stevens 7-Apr-2015
#
#   Environment:
#
#       User Mode
#
################################################################################

BINARY = perflib.so

BINARYTYPE = so

BINPLACE = bin

INCLUDES += $(SRCROOT)/os/apps/libc/include;

OBJS = perflib.o  \

include $(SRCROOT)/os/minoca.mk

